### ISSUE TITLE
Multiple errors trying to run on basic 

### ISSUE THREAD

**Issue by bugeaud** [crazy-max/ftp-sync#13]
Trying to run v2.03 on Transcend WiFi SD Linux fail with the following errors :

# bash -x /etc/init.d/ftp-sync .
+
: not found/ftp-sync: line 10:
+
: not found/ftp-sync: line 44:
+ CONFIG_FILE=/etc/ftp-sync/ftp-sync.conf
+
: not found/ftp-sync: line 46:
+
: not found/ftp-sync: line 48:
+
: not found/ftp-sync: line 50:
/etc/init.d/ftp-sync: line 51: syntax error: unexpected "("

**Comment by crazy-max** [comment]
Will be hard to reproduce your problem on this kind of linux based distribution :/
Can you provide more information about this distrib ?
