### ISSUE TITLE
Continue downloads

### ISSUE THREAD

**Issue by r000d** [crazy-max/ftp-sync#14]
First of all, thanks for the script!
I love the idea if storing md5 of downloaded files.
What about continuable downloads in case of large files/slow connection?
I tried the option "-C -" for curl (wget has a similar option) and it seems to work fine after restarting the script.
Is there a reason you didn't include this option?

**Comment by crazy-max** [comment]
Hi,

Yes indeed thanks for contrib!

**Comment by crazy-max** [comment]
Will be added in the next release

**Comment by crazy-max** [comment]
Solved in release 3.0.
Please note that you have to edit the config file `ftp-sync.conf` if you upgrade from a previous release!
