### ISSUE TITLE
SFTP option

### ISSUE THREAD

**Issue by jacobkossman** [crazy-max/ftp-sync#15]
I don't think curl has a built in sftp option right? I think that's the only thing missing from this script! Awesome job but I won't use it until I can do encrypted / secure transfers. Could you add this option? Thanks!

**Comment by crazy-max** [comment]
Hi,

Yes it's possible to use curl with sftp but this requires libssh2 and libssh2-devel packages.
Good suggestion btw and thanks for your feedback.

**Comment by crazy-max** [comment]
FTP SSL / TLS will be added for curl and wget in the next release!

**Comment by crazy-max** [comment]
Solved in release 3.0. FTPS is only available for curl.
Please note that you have to edit the config file `ftp-sync.conf` if you upgrade from a previous release!
