### ISSUE TITLE
One time

### ISSUE THREAD

**Issue by bentux** [crazy-max/ftp-sync#16]
Hello
It is possible that a file could be download juste one time? I want to be able to delete the destination file without the script download again. Or it is possible to delete the source when the file is download?

Regards

**Comment by crazy-max** [comment]
Hi,

Actually the file is already downloaded only one time with the script by saving his hash.

**Comment by bentux** [comment]
So maybe I have a trouble with the md5 file.
In fact I havn't any md5 file on /etc/ftp-sync/
```
admin@Syno:/etc/ftp-sync$ dir
total 32
drwxrwxrwx  2 root root  4096 Feb 28 13:53 .
drwxr-xr-x 48 root root  4096 Feb 28 06:03 ..
-rwxrwxrwx  1 root root 17559 Feb 19 15:24 ftp-sync
-rw-r--r--  1 root root   494 Feb 26 17:57 ftp-sync.conf
```

If the the file is already in the dir It show that
```
admin@Syno:/etc/ftp-sync$ sudo ./ftp-sync /volume1/Admin/download/
FTP Sync v2.03 (2016/02/28 13:51:35)
--------------
Checking connection to ftp://poolxxx.seedbox.fr:21/series/...
Successfully connected!
--------------
Script PID: 23009
Source: ftp://poolxxx.seedbox.fr:21/series/
Destination: /volume1/Admin/download/
Log file: /var/log/ftp-sync/20160228135135.log
Download method: wget
MD5 method: text
--------------
Process file : xxxxxxxxxxxxxxxxx.avi
Hash: 4813a313ce4a22ebc7ec188bb62b1573
Size: 331.11 Mb
Status : Already downloaded and valid. Skip download...
Time spent: 00:00:00
--------------
Finished...
Total time spent: 00:00:01
```

But if I delete the file
```
admin@Syno:/etc/ftp-sync$ sudo ./ftp-sync /volume1/Admin/download/
FTP Sync v2.03 (2016/02/28 13:56:56)
--------------
Checking connection to ftp://poolxxx.seedbox.fr:21/series/...
Successfully connected!
--------------
Script PID: 23934
Source: ftp://poolxxx.seedbox.fr:21/series/
Destination: /volume1/Admin/download/
Log file: /var/log/ftp-sync/20160228135656.log
Download method: wget
MD5 method: text
--------------
Process file : xxxxx.avi
Hash: 4813a313ce4a22ebc7ec188bb62b1573
Size: 331.11 Mb
Status : Never downloaded...
Start download to /volume1/Admin/download/ xxxxx.avi... Please wait...
File successfully downloaded!
Time spent: 00:04:09
--------------
Finished...
Total time spent: 00:04:09
```

The file will be download again.

**Comment by crazy-max** [comment]
Can you post your ``ftp-sync.conf`` ?
What is your operating system ?

**Comment by bentux** [comment]
```
# FTP
FTP_HOST="poolxxx.seedbox.fr"
FTP_PORT="21"
FTP_USER="username"
FTP_PASSWORD="password"
FTP_SRC="/series"

# Download
DL_USER=""
DL_GROUP=""
DL_CHMOD=""
DL_REGEX=""
DL_RETRY=3
DL_METHOD="wget"
DL_HIDE_SKIPPED=0
DL_HIDE_PROGRESS=1

# MD5
MD5_ENABLED=1
MD5_METHOD="text"
MD5_DIR="/etc/ftp-sync/"
```


I use DSM 6 RC today

**Comment by crazy-max** [comment]
Can you check the user who launch ftp-sync and permissions rights in /etc/ftp-sync/ ?

Maybe you have to override owner :
```
chown -R user.group /etc/ftp-sync/
```

**Comment by bentux** [comment]
It's launching by root on crontab in DSM
I do a 
`chmod -R root:root /etc/ftp-sync/`
But nothing change
On DSM we haven't init.d dir is it a problem?

**Comment by crazy-max** [comment]
Have you check the synology section in Readme.md ?
Maybe there is an issue with dsm 6, i have only check dsm 5.2.
I'll keep you in touch.

**Comment by bentux** [comment]
Yes I do, twice :)
Thank's for your job

**Comment by crazy-max** [comment]
I have installed DSM_DS3615xs_7135 on a VirtualBox (via XPEnoboot_DS3615xs_5.2-5592.2) and i have found the problem.

**Comment by bentux** [comment]
Vert good news :)

**Comment by crazy-max** [comment]
Solved in release 3.0.
Please note that you have to edit the config file `ftp-sync.conf` if you upgrade from a previous release!

**Comment by bentux** [comment]
You're a boss men. I just install the 3.0 and it's ok.
Many thanks

**Comment by crazy-max** [comment]
Nice :)
