### ISSUE TITLE
Need to run as root/sudo

### ISSUE THREAD

**Issue by georgebohnisch** [crazy-max/ftp-sync#19]
When running as the local user, the script fails to create /var/run/ftp-sync.pid and the log files associated with the sync.

I'm required to run the script as a sudo user.

Any workarounds?

**Comment by crazy-max** [comment]
Indeed there is an issue. I have to add a `whoami` directive to check the current user.
For the moment you can edit the `ftp-sync.conf` file and change `PID_FILE="/var/run/ftp-sync.pid"` to `PID_FILE="/var/run/ftp-sync/ftp-sync.pid"`

Then enter the following commands :
```
mkdir /var/run/ftp-sync
mkdir /var/log/ftp-sync
chown ${USER:=$(/usr/bin/id -run)}:$USER /var/run/ftp-sync /var/log/ftp-sync
```

**Comment by crazy-max** [comment]
I have added messages to check permission issue in 3.2 release.
But i have to make an installer to allow non root users to use the script.
