### ISSUE TITLE
Allow multiple instances

### ISSUE THREAD

**Issue by MartinGantenbein** [crazy-max/ftp-sync#22]
Would be nice to be able to have configurations for more than one FTP host or more than one FTP user on the same host. Maybe simply add a parameter to specify the conf file, defaults to ftp-sync.conf

**Comment by crazy-max** [comment]
I can implement this feature with a conf.d folder for example containing multiple config files

**Comment by crazy-max** [comment]
For this improvement a refactoring have been made and now you will have to pass the config file as argument instead of the destination folder.

Example : `/etc/init.d/ftp-sync seedbox.conf`
Each config file has to be located in the folder `/opt/ftp-sync/conf`
